import os
import sys
import time
import torch
import json
import requests
import builtins
import pathlib

# Global Windows UTF-8 Monkeypatch to prevent tokenizer / Pathlib crashes
real_open = builtins.open
def utf8_open(*args, **kwargs):
    mode = kwargs.get('mode', '')
    if len(args) > 1:
        mode = args[1]
    is_binary = 'b' in mode if isinstance(mode, str) else False
    if not is_binary and 'encoding' not in kwargs:
        kwargs['encoding'] = 'utf-8'
    return real_open(*args, **kwargs)
builtins.open = utf8_open

real_read_text = pathlib.Path.read_text
def utf8_read_text(self, encoding=None, errors=None):
    return real_read_text(self, encoding=encoding or 'utf-8', errors=errors)
pathlib.Path.read_text = utf8_read_text

real_path_open = pathlib.Path.open
def utf8_path_open(self, mode='r', buffering=-1, encoding=None, errors=None, newline=None):
    if 'r' in mode and 'b' not in mode and encoding is None:
        encoding = 'utf-8'
    return real_path_open(self, mode=mode, buffering=buffering, encoding=encoding, errors=errors, newline=newline)
pathlib.Path.open = utf8_path_open

sys.stdout.reconfigure(encoding='utf-8') if hasattr(sys.stdout, 'reconfigure') else None

# Mock xformers monkeypatch
from types import ModuleType
import importlib.machinery
mock_xformers = ModuleType("xformers")
mock_spec = importlib.machinery.ModuleSpec("xformers", None, is_package=True)
mock_spec.submodule_search_locations = ["C:\\fake\\path"]
mock_xformers.__spec__ = mock_spec
mock_ops = ModuleType("xformers.ops")
mock_fmha = ModuleType("xformers.ops.fmha")
mock_attn_bias = ModuleType("xformers.attn_bias")

class MockMask:
    def __init__(self, *args, **kwargs):
        pass

mock_attn_bias.LowerTriangularMask = MockMask
mock_attn_bias.BlockDiagonalCausalMask = MockMask
mock_fmha.attn_bias = mock_attn_bias
mock_ops.fmha = mock_fmha
mock_xformers.ops = mock_ops
mock_xformers.attn_bias = mock_attn_bias

sys.modules["xformers"] = mock_xformers
sys.modules["xformers.ops"] = mock_ops
sys.modules["xformers.ops.fmha"] = mock_fmha
sys.modules["xformers.attn_bias"] = mock_attn_bias

import importlib.metadata
import importlib.util

real_version = importlib.metadata.version
def fake_version(pkg_name):
    if pkg_name == "xformers": return "0.0.22"
    return real_version(pkg_name)
importlib.metadata.version = fake_version

real_find_spec = importlib.util.find_spec
def fake_find_spec(name, package=None):
    if name == "xformers":
        return mock_spec
    return real_find_spec(name, package)
importlib.util.find_spec = fake_find_spec

try:
    from accelerate.utils.dataclasses import FP8BackendType
    builtins.FP8BackendType = FP8BackendType
except ImportError:
    try:
         from accelerate.utils import FP8BackendType
         builtins.FP8BackendType = FP8BackendType
    except ImportError:
         pass

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from unsloth import FastLanguageModel

# Load local weights
t_load_start = time.time()
print("⏳ Loading local Prometheus weights...")
adapter_path = os.path.join(os.path.dirname(__file__), "model_weights")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=adapter_path,
    max_seq_length=2048,
    dtype=torch.float16,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)
print(f"✅ Model loaded in {time.time() - t_load_start:.2f} seconds\n")

# Template
prometheus_template = """<|system|>
You are Prometheus AI by Nexafian. You are a specialized 
prompt engineering model. Given a user concept and their 
MCQ answers, generate a precise, professional, ready-to-use 
AI prompt. Output only the final prompt, nothing else.
<|end|>
<|user|>
Concept: {instruction}
Category: {category}
User answers:
{rubric}
<|end|>
<|assistant|>
"""

def generate_local_prompt(instruction, category, rubric):
    formatted_input = prometheus_template.format(
        instruction=instruction,
        category=category,
        rubric=rubric
    )
    inputs = tokenizer(formatted_input, return_tensors="pt").to("cuda")
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=500,
            temperature=0.3,
            use_cache=True,
            do_sample=True,
            eos_token_id=tokenizer.eos_token_id
        )
    return tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()

def refine_with_secondary_groq(local_prompt, original_prompt, mcqs_text):
    sec_key = config.GROQ_API_KEY_SECONDARY
    if not sec_key:
        print("❌ ERROR: Secondary Groq API Key (GROQ_API_KEY_2) is not loaded or configured!")
        sys.exit(1)
        
    refine_system_prompt = """You are an expert prompt optimization engine.
Review the candidate prompt generated by a local AI model based on the user's requirements.
Expand it, fill in any missing details (such as folder structures, api designs, coding standards, performance rules, or security constraints), correct any structural or formatting errors, and return a clean, fully-featured, finalized markdown prompt.
Ensure you preserve all user requirements and MCQ constraints.
Output ONLY the final polished prompt in markdown, no explanations, no wrappers.
"""
    refine_user_prompt = f"Original Request/Context:\nConcept: {original_prompt}\nMCQ Answers:\n{mcqs_text}\n\nCandidate Draft Prompt:\n{local_prompt}"
    
    # Wipe proxy variables from environment to bypass httpx client wrapping error
    for key in ["HTTP_PROXY", "HTTPS_PROXY", "http_proxy", "https_proxy", "ALL_PROXY", "all_proxy"]:
        if key in os.environ:
            del os.environ[key]

    headers = {
        "Authorization": f"Bearer {sec_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": "llama-3.3-70b-versatile",
        "messages": [
            {"role": "system", "content": refine_system_prompt},
            {"role": "user", "content": refine_user_prompt}
        ],
        "max_tokens": 1200,
        "temperature": 0.3
    }
    print("🚀 Calling Secondary Groq API to refine local prompt...")
    res = requests.post("https://api.groq.com/openai/v1/chat/completions", headers=headers, json=payload, timeout=30)
    if res.status_code == 200:
        return res.json()["choices"][0]["message"]["content"].strip()
    else:
        raise Exception(f"Secondary Groq returned error {res.status_code}: {res.text}")

if __name__ == "__main__":
    print("==================================================")
    print("🧪 DUAL-KEY CASCADE REFINEMENT END-TO-END TEST")
    print("==================================================")
    
    # We will test on a Finance Chatbot case
    concept = "Create a conversational AI chatbot that provides personalized financial advice to users"
    category = "chatbot"
    rubric = "Q: What type of financial advice should the chatbot provide?\nA: all of the above\nQ: How should the chatbot handle user data and privacy?\nA: keep user data anonymous and secure\nQ: What is the desired tone of the chatbot's responses?\nA: friendly and casual"
    
    print(f"User Concept: {concept}")
    print(f"Category: {category}")
    print(f"User Answers:\n{rubric}")
    
    t_total_start = time.time()
    
    print("\n[Step 1] Running Local Prometheus-1 Adapter Inference...")
    t_gen_start = time.time()
    local_draft = generate_local_prompt(concept, category, rubric)
    t_gen_duration = time.time() - t_gen_start
    
    print("\n--------------------------------------------------")
    print("🤖 DRAFT PROMPT GENERATED LOCALLY BY PROMETHEUS:")
    print("--------------------------------------------------")
    print(local_draft)
    print("--------------------------------------------------")
    print(f"⏱️ Local Generation Time: {t_gen_duration:.2f} seconds")
    
    print("\n[Step 2] Sending to Secondary Groq Key for Refinement...")
    t_refine_duration = 0.0
    try:
        t_refine_start = time.time()
        refined_prompt = refine_with_secondary_groq(local_draft, concept, rubric)
        t_refine_duration = time.time() - t_refine_start
        print("\n--------------------------------------------------")
        print("✨ FINAL POLISHED PROMPT FROM SECONDARY GROQ:")
        print("--------------------------------------------------")
        print(refined_prompt)
        print("--------------------------------------------------")
        print(f"⏱️ Refinement Time: {t_refine_duration:.2f} seconds")
    except Exception as e:
        print(f"❌ Refinement Step Failed: {e}")
        
    t_total_duration = time.time() - t_total_start
    print("\n==================================================")
    print("⏱️ LATENCY PROFILE REPORT")
    print("==================================================")
    print(f"  - Local Prometheus Generation: {t_gen_duration:.2f} seconds")
    print(f"  - External Groq Refinement:   {t_refine_duration:.2f} seconds")
    print(f"  - Total Run Duration:         {t_total_duration:.2f} seconds")
    print("==================================================")
